// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdClVMie-b6YImJWG3vFFTi8gFIz78q8',
    appId: '1:186770024187:web:7d114dbcbea25595c3f25e',
    messagingSenderId: '186770024187',
    projectId: 'ok-kam-langkai',
    authDomain: 'ok-kam-langkai.firebaseapp.com',
    storageBucket: 'ok-kam-langkai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAh2gxfln0_R_y1TFI86rfb6edoeO71M',
    appId: '1:186770024187:android:68c7f92f967a2d99c3f25e',
    messagingSenderId: '186770024187',
    projectId: 'ok-kam-langkai',
    storageBucket: 'ok-kam-langkai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaS02Gad1463sYgkeQ5MaQ-gyJrjdygo4',
    appId: '1:186770024187:ios:52fed4e680149128c3f25e',
    messagingSenderId: '186770024187',
    projectId: 'ok-kam-langkai',
    storageBucket: 'ok-kam-langkai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaS02Gad1463sYgkeQ5MaQ-gyJrjdygo4',
    appId: '1:186770024187:ios:52fed4e680149128c3f25e',
    messagingSenderId: '186770024187',
    projectId: 'ok-kam-langkai',
    storageBucket: 'ok-kam-langkai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkdClVMie-b6YImJWG3vFFTi8gFIz78q8',
    appId: '1:186770024187:web:27a2b18159c10b40c3f25e',
    messagingSenderId: '186770024187',
    projectId: 'ok-kam-langkai',
    authDomain: 'ok-kam-langkai.firebaseapp.com',
    storageBucket: 'ok-kam-langkai.appspot.com',
  );
}
